- hosts: win
  vars:
    app1: office2019
    app2: chrome
    app3: firefox
    app4: vmware
    app5: bigfix
    app6: laps
    app7: syslog
    app8: adobe
 
  tasks:
    - name: Create Temp folder
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
  
    - name: copy All installation media
      ansible.windows.win_copy:
        src: ./bits
        dest: c:\temp

    - name: Installs {{ app1 }} 
      ansible.windows.win_shell: C:\temp\{{ app1 }}\installoffice2019.cmd >> C:\temp\{{ app1 }}.txt
      args:
        chdir: c:\temp\{{ app1 }}

    - name: Install {{ app2 }}
      win_package:
        path: c:\temp\{{ app2 }}\GoogleChromeStandaloneEnterprise64.msi
        state: present


    - name: Install {{ app3 }}
      win_package:
        path: c:\temp\{{ app3 }}\Firefox.msi
        state: present


    - name: install {{ app5 }}
      ansible.windows.win_shell: c:\temp\{{ app5 }}\BigFix-BES-Client-10.0.7.52.exe /S /v/qn
      args:
        chdir: c:\temp\{{ app5 }}

    - name: Install {{ app6 }}
      win_package:
        path: c:\temp\{{ app6 }}\LAPS.x64.msi
        state: present


    - name: install {{ app7 }}
      ansible.windows.win_shell: c:\temp\{{ app7 }}\syslogagent.exe -install 192.168.1.100
      args:
        chdir: c:\temp\{{ app7 }}

    - name: install {{ app8 }}
      ansible.windows.win_shell: c:\temp\{{ app8 }}\adobe.exe /sALL
      args:
        chdir: c:\temp\{{ app8 }}


    - name: Let's decrapify this image
      ansible.windows.win_shell: c:\temp\decrapify.ps1 >> c:\temp\decrapify.txt
      args:
        chdir: c:\temp

    - name: Cleanup Temp Folder
      ansible.windows.win_file:
        path: C:\Temp
        state: absent


