---
- hosts: jenkins
  gather_facts: no
  tasks:

  - name: Create Temp folder
    ansible.windows.win_file:
      path: C:\Temp
      state: directory

  - name: Copy Jenkins bits into ansible working directory
    ansible.builtin.copy:
      src: /home/jenkins/repos/jenkins
      dest: .

  - name: Copy Jenkins bits to windows server
    ansible.windows.win_copy:
      src: ./jenkins
      dest: c:\temp L


  - name: Install Java
    win_package:
      path: c:\temp\jenkins\jdk17.msi
      state: present
  
  - name: Installs Jenkins on port 80
    ansible.windows.win_shell: msiexec /i "c:\temp\jenkins\jenkins.msi" /qn /norestart JAVA_HOME="C:\Program Files\Java\jdk-17" PORT=80 /L*v jenkins.log
    args:
      chdir: c:\temp\jenkins
