- name: deploy {{ vm_name }} from template demo
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars.yml
  collections:
    - community.vmware
  tasks:

  - name: Revert to a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_host }}"
      username: "{{ username_secret }}"
      password: "{{ password_secret }}"
      datacenter: "{{ datacenter_name }}"
      folder: "/{{ datacenter_name }}/vm/"
      name: "{{ vm_name }}"
      state: revert
      snapshot_name: "{{ snap_name }}"
    delegate_to: localhost