---
# tasks file for wsus-disk
- name: Add disks to virtual machine using {{ vm_name }}
  community.vmware.vmware_guest_disk:
    hostname: "{{ vcenter_host }}"
    username: "{{ username_secret }}"
    password: "{{ password_secret }}"
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name }}"
    disk:
      - size_tb: 1
        type: thin
        datastore: "{{ datastore }}"
        state: present
        scsi_controller: 0
        unit_number: 1
        scsi_type: 'lsilogic'
        disk_mode: 'independent_persistent'