---
# tasks file for wsus_disk_config
- name: Create {{ app }} Directory
  ansible.windows.win_file:
    path: C:\Temp\{{ app }}
    state: directory

- name: Copy {{ name }}
  ansible.windows.win_copy:
    src: ../files/*
    dest: c:\temp\{{ app }}

- name: Installs {{ name }} 
  ansible.windows.win_shell: C:\temp\{{ app }}\{{ installer }} /s ./files/disk_config.txt
  args:
    chdir: c:\temp\{{ app }}

- name: Cleanup {{ name }}
  ansible.windows.win_file:
    path: C:\Temp\{{ app }}
    state: absent