---
# tasks file for wsus_disk_config
- name: Create {{ app }} Directory
  ansible.windows.win_file:
    path: C:\Temp\{{ app }}
    state: directory

- name: Copy {{ name }}
  ansible.windows.win_copy:
    src: ../files/
    dest: c:\temp\{{ app }}

- name: Installs {{ name }} 
  ansible.windows.win_shell: diskpart.exe /s disk_config.txt
  args:
    chdir: c:\temp\{{ app }}

- name: Cleanup {{ name }}
  ansible.windows.win_file:
    path: C:\Temp\{{ app }}
    state: absent

- name: Install WSUS Server Role
  ansible.windows.win_feature:
    name: UpdateServices
    include_management_tools: yes
    state: present

- name: Create {{ app }} Directory
  ansible.windows.win_file:
    path: d:\WSUS
    state: directory

- name: Configure WSUS
  ansible.windows.win_shell: .\wsusutil.exe postinstall CONTENT_DIR=D:\WSUS
  args:
    chdir: C:\Program Files\Update Services\Tools

- name: Category Sync
  ansible.windows.win_powershell:
    script: |
      #Get WSUS Server Object

      $wsus = Get-WSUSServer

      #Connect to WSUS server configuration

      $wsusConfig = $wsus.GetConfiguration()

      

      #Set to download updates from Microsoft Updates

      Set-WsusServerSynchronization –SyncFromMU

      

      #Set Update Languages to English and save configuration settings

      $wsusConfig.AllUpdateLanguagesEnabled = $false           

      $wsusConfig.SetEnabledUpdateLanguages(“en”)           

      $wsusConfig.Save()

      

      #Get WSUS Subscription and perform initial synchronization to get latest categories

      $subscription = $wsus.GetSubscription()

      $subscription.StartSynchronizationForCategoryOnly()

      

      While ($subscription.GetSynchronizationStatus() -ne ‘NotProcessing’) {

          Write-Host “.” -NoNewline

          Start-Sleep -Seconds 5

      }

      Write-Host “Sync is done.”



- name: Perform Initial Sync
  ansible.windows.win_powershell:
    script: |


      Get-WsusProduct | where-Object {

          $_.Product.Title -in (

          'Office 2016',

          'Windows 10',

          'Windows Server 2012 R2',

          'Windows Server 2012',

          'Windows Server 2016',

          'Windows Server 2019',

          'Exchange Server 2016',
          
          'Microsoft SQL Server 2012',

          'Microsoft SQL Server 2014',

          'Microsoft SQL Server 2016',

          'Microsoft SQL Server 2017',

          'Microsoft SQL Server 2019',

          'Microsoft SQL Server Management Studio v17',

          'Microsoft SQL Server Management Studio v18',

          'Microsoft SQL Server Management Studio v19',

          'Powershell',

          'Microsoft Defender Antivirus',

          'Windows 10 LTSB',

          'Windows 10, version 1903 and later',

          'Windows 10, version 1903 and later, Upgrade & Servicing Drivers',

          'Windows 10, version 1809 and later, Upgrade & Servicing Drivers',

          'Windows 10 Version 1803 and Later Upgrade   & Servicing Drivers',

          'Active Directory'

          )


      } | Set-WsusProduct

      

      #Configure the Classifications

      Get-WsusClassification | Where-Object {

          $_.Classification.Title -in (

          'Update Rollups',

          'Security Updates',

          'Critical Updates',

          'Service Packs',

          'Updates')

      } | Set-WsusClassification

      

      #Configure Synchronizations

      $subscription.SynchronizeAutomatically=$true

      #Set synchronization scheduled for midnight each night

      $subscription.SynchronizeAutomaticallyTimeOfDay= (New-TimeSpan -Hours 0)

      $subscription.NumberOfSynchronizationsPerDay=1

      $subscription.Save()

      

      #Kick off a synchronization

      $subscription.StartSynchronization()



